version: 0.2
phases:
  install:
    commands:
      - echo install phase...
      - curl https://github.axa.com/axa-general-insurance
      - git clone https://git:2390c7d3276c96d895ced9066737a1462c473d08@github.axa.com/axa-general-insurance/iac-test.git
      - env
  pre_build:
    commands:
      - echo pre_build phase...
      - env
  build:
    commands:
      - echo build phase...
      - env
  post_build:
    commands:
      - echo post_build phase...
      - env
